CREATE DATABASE IF NOT EXISTS ai_usecase_db
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ai_usecase_db;

CREATE TABLE IF NOT EXISTS use_cases (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(500),
  dept VARCHAR(255),
  payload JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
